### ISSUE TITLE
Task 9 plots

### ISSUE THREAD

**Issue by Norahelgeland** [anderkve/FYS3150#101]
Hello,

We are a bit confused regarding our plots from task 9. 

For one slit we get the following plot:

![image](https://user-images.githubusercontent.com/113336634/206419855-4ccdd397-c764-49cb-8ff2-a99d52864112.png)

For two slits we get the following plot:

![image](https://user-images.githubusercontent.com/113336634/206421888-b79eda7d-a8f5-4fe2-94d5-e2ce36c44080.png)

We expected to observe three peaks for one slit and more peaks for two slits, and we are wondering why it is not symmetric. Is it just because the distance from the slit is too great?  Also our heat map for two slits looks like it has three peaks, but this does not show up in the plot for x = 0.8.

Here is our heat map plot for t = 0.002:

![image](https://user-images.githubusercontent.com/113336634/206421556-121b9364-c5da-4067-8d79-da8904cb040b.png)

**Comment by anderkve** [comment]
Hi @Norahelgeland!

Indeed, these results don't look correct. There may be multiple sources of error, but the most striking problem is how jagged the lines are, corresponding to the strange block-like pattern in the bottom heat map. 

My guess would be that there is something wrong with your A and B matrices, or with the code that translates from indices (i,j) to index k. So that is where I'd start looking. A common mistake is to have a code for constructing A and B that works for the (M-2)=3 example matrices in the project description, but doesn't work for general values of M-2. If you suspect this may be the problem, it can worth working/thinking through what these matrices would look like for  M-2=2 and M-2=4, to see the correct pattern.

To test the code I would focus first on the case with zero potential, i.e. just a freely propagating wave packet, and make sure that this looks sensible before you start adding slit potentials.

**Comment by Norahelgeland** [comment]
Thank you! It turned out that there was a mistake in the sub matrices of our A and be matrices. Now the plots look more correct :)
