### ISSUE TITLE
Header-only libraries

### ISSUE THREAD

**Issue by ngrlcu** [anderkve/FYS3150#105]
Just to be sure, is it "legal" to add header-only libraries?

**Comment by anderkve** [comment]
Hi @ngrlcu!

It's certainly legal, but if you put large-ish function/class definitions in the header file you might get some negative comment on code style. 

None of this is set in stone, but the general consensus for code style in C++ is that function/class definitions belong in .cpp files, while only the declarations are kept in the .hpp files. Though, for short functions (for some not-fully-agreed-upon definition of "short") it is also quite common to put the full definition in the .hpp file.

This hpp/cpp division is what we have advocated in the course, hence the possible negative comment/score if you choose a very different approach. 

There are of course pros and cons to different approaches, see e.g. the discussions [here](https://stackoverflow.com/questions/12671383/benefits-of-header-only-libraries) and [here](https://stackoverflow.com/questions/583255/is-it-a-good-practice-to-place-c-definitions-in-header-files). 

 In my own experience, there are three main reasons why I prefer a hpp/cpp split:

 - Avoids "multiple definitions" problems (a problem at the linking stage)
 - Putting everything in headers increases compilation time, since if you make a change in a header file all files that include that header must be recompiled. (Mostly a problem in larger projects, but then it does become a very significant issue!)
 - Having nothing but declarations in the header file means that it effectively reads like a documentation of the "user interface" (API) from the point of view of the rest of the code. I.e., it's easy to quickly look at the hpp file to get an overview of which functions exist and how to use them, without having to scroll through the full definitions.

**Comment by ngrlcu** [comment]
Oh thanks a lot for the deep explanation! I truly found it interesting.
But I badly expressed myself: even thou that was indeed a question I had in mind (more of a curiosity of mine), I wanted to ask if we can add to our `include/` an _external_ header-only. 
Your answer is kind of related to that, but probably in this case there is an exception(?).  I guess the major problem, in this case, is that we include someone else's work.
The external library is just (this)[https://github.com/gipert/progressbar],  it is not a lot of code...

**Comment by anderkve** [comment]
> I wanted to ask if we can add to our include/ an external header-only.

Ah, I see!  :) 

> I wanted to ask if we can add to our include/ an external header-only. Your answer is kind of related to that, but probably in this case there is an exception(?). I guess the major problem, in this case, is that we include someone else's work.

In this case it's perfectly fine for you to include the progressbar header with your code, since

- The license of the external library (check the top of progressbar.hpp) allows you to copy/use/modify/redestribute it as you want (as long as you keep the MIT license text)
- The external code you are using not related to a key task in the project that you were supposed to solve yourself.

Good luck with finishing the project!

**Comment by ngrlcu** [comment]
perfect thanks again!
