### ISSUE TITLE
Error in 'Additional setup for M1 Mac users'

### ISSUE THREAD

**Issue by Daniel-Haas-B** [anderkve/FYS3150#28]
Hey everyone! Maybe this is silly but just wanted to post here in case anyone has the same problem I had.

While following the instructions to 'Additional setup for M1 Mac users', I kept getting the error:

> zsh: no matches found: /opt/homebrew/Cellar/armadillo/10.6.2/lib/*

To solve that, I just used the quotes in both commands:

`sudo cp -r '/opt/homebrew/Cellar/armadillo/10.6.2/lib/* /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib'
`

`sudo cp -r '/opt/homebrew/Cellar/armadillo/10.6.2/include/armadillo* /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include'`

Hope it helps someone :)

**Comment by anderkve** [comment]
Hi @Daniel-Haas-B -- thanks for pointing out this problem! 

Turns out this is related to the question of which type of Unix shell one is using (e.g. `zsh` vs `bash`). I've added a [section](https://anderkve.github.io/FYS3150/book/getting_ready/mac_users.html#choosing-a-unix-shell) at the beginning of our Mac page that explains what's going on, and how to switch between `zsh` vs `bash` on macOS.
