### ISSUE TITLE
understanding the error function O(h)

### ISSUE THREAD

**Issue by Madssb** [anderkve/FYS3150#37]
is it such that for O(h^3) /h^2 = O(h)?, why or why not?

**Comment by anderkve** [comment]
Hi @Madssb,

Yes, O(h^3) / h^2 = O(h)

Big-O notation answers this question "How does my function behave as the argument goes towards a given limit?"

When we discuss algorithms and e.g. say that some algorithm is O(N^3), the function we're thinking of is the total time required, or the number of FLOPs, and the input argument is N, which denotes the size of our problem. In that case the limit we are thinking of is N --> infinity.

Say that the exact function was something like 5 * N^3 + 2 * N^2 - 3 * log(N) + 100. This function would be O(N^3) since when N is large enough, this function will behave just like the function N^3. (The other terms become irrelevant when N is very large.) If you now take an O(N^3) expression like that and divide by N^2, the dominant term towards the limit N --> infinity will still be the first term, but that term is now 5 * N, in other words, the entire function now has a O(N) behaviour as N --> infinity.  

When considering e.g. series expansions in some small stepsize h, the limit we are thinking of is h --> 0. So in this case it is the term with the *smallest* power of h that will be the dominant term towards the limit. I.e. a series expansions that goes like 5 * h^3 - 7 * h^4 + 9 * h^5 - ... we can denote as O(h^3), since the h^3 term is the dominant one in the limit h --> 0.

If we take this entire series and divide by h^2, it will still be the first term that dominates in the limit h --> 0. But that term will now have h rather than h^3 dependence, so we can denote that resulting series as O(h).

You can read more about Big-O notation and its mathematical properties here: https://en.wikipedia.org/wiki/Big_O_notation
