### ISSUE TITLE
Const and reference (&) in function arguments

### ISSUE THREAD

**Issue by JohanCarlsen** [anderkve/FYS3150#44]
Hi!
Consider this mock program:
```
void func(const double& x){
     x += 2.;
}
double y = 0.;
func(y);
```
The `const` means that the user cannot change the variable `x`, right? And the `&` is a reference, such that `x` and `y` are one and the same?

But when the `const` makes `x`not changeable, does that not apply to `y`? How exactly does this work?

**Comment by anderkve** [comment]
Hi @JohanCarlsen!

Thanks for the question -- this a useful example to clarify how these things work. 

> The const means that the user cannot change the variable x, right?

Correct.

> And the & is a reference, such that x and y are one and the same?

Correct. `x` is here just the local name used inside the function `func` to for whatever variable reference was passed in as input (here a reference to the variable `y`).

> But when the const makes x not changeable, does that not apply to y? How exactly does this work?

What will happen here is that the program will simply fail to compile, exactly because of the inconsistency you point out: that your function `func` is trying to assign a new value (`x += 2`) to a reference that has been declared `const`. 

To quickly confirm this, I pasted your code into cpp.sh, which is an online C++ test page: https://cpp.sh/?source=void+func(const+double%26+x)%0A%7B%0A++++x+%2B%3D+2.%3B%0A%7D%0A%0A%0Aint+main()%0A%7B%0A%0A++++double+y+%3D+0.%3B%0A++++func(y)%3B%0A%0A++++return+0%3B%0A%7D

Just hit the `Run` button and you'll see the compilation error pointing to the `x += 2` line.

If you remove `const` from the `func` function signature, this program will compile fine and running it will modify the `y` variable. And of course, if you keep `const` but remove `x += 2`, the program will compile fine and running it will do absolutely nothing. :)

**Comment by JohanCarlsen** [comment]
Ok thank you 😊
