### ISSUE TITLE
About the particle simulation

### ISSUE THREAD

**Issue by JohanCarlsen** [anderkve/FYS3150#59]
When we are supposed to simulate the movement for 100 $\mu s$, my particles are more or less coloring the entire figure.. I do 
`int total_time = 100;`
`double dt = 1e-3;`
`int steps = total_time / dt;`
Is this wrong?

**Comment by JohanCarlsen** [comment]
![animation](https://user-images.githubusercontent.com/90179340/194613050-0c35f3b1-672f-4569-b981-0d115d83ca61.gif)

This is how it looks for a simulation of $t=1 \mu s$

**Comment by JohanCarlsen** [comment]
I had forgotten the mass. I was testing, so I had mass equal to 1. Now it looks like this:
![animation](https://user-images.githubusercontent.com/90179340/194709765-94ef05a3-3cdd-4de6-89b7-237eb3aefc28.gif)

**Comment by JohanCarlsen** [comment]
Yes, thank you! 
Wien I changed the mass from 1 u to 40.078, things were looking much better!

**Comment by anderkve** [comment]
That's good to hear! (Note that I've discovered another mistake in the initial values I have chosen for Problem 8, so they will be updated once more later this evening... Sorry for the confusion.)

**Comment by JohanCarlsen** [comment]
May I ask why you have chosen the initial values you have? Is it a specific reason, or just a way of being able to spot if someone has done something wrong?

**Comment by anderkve** [comment]
Exactly, it's mostly just because it's much easier to  easy to spot mistakes when everyone is using the same initial values. Last year many students spent quite some time looking for mistakes in codes that turned out to be perfectly correct, just because the simulation results for particular initial values looked surprising.

And the reason why I had a "mistake" in my original choice of initial values was just that our analytical expression for the single-particle case assumes that y_0 = 0 and v0_x = v0_z = 0, which I had forgot about when I chose the initial values for Problem 8.
