### ISSUE TITLE
Bruk av eksempelkode 

### ISSUE THREAD

**Issue by nevlunghavn** [anderkve/FYS3150#6]
Kan eksempelkode fra kurset brukes fritt uten at det blir sett på som plagiat?

**Comment by anderkve** [comment]
Hei @nevlunghavn! I'll reply in English so that everyone in the course can read it. (The question above is whether you can freely use code examples from the course page and this git repo without it being regarded as plagiarism when we assess your projects)

**Yes**, all example codes in this course can be freely used, and we will not regard it as plagiarism. However, I would recommend that you get into the habbit of always mentioning things like this in some comments at the top of the relevant files. E.g. a comment like this
```
// This file uses code from https://github.com/anderkve/FYS3150
```  
or
```
// This code is based on examples from https://github.com/anderkve/FYS3150
``` 

Sometimes it also nice to be more specific, e.g.
```
// The code for timing of algorithms is taken from https://github.com/anderkve/FYS3150
```

**Comment by nevlunghavn** [comment]
Thank you for the info and the recommended guidelines.
