### ISSUE TITLE
Forward Euler

### ISSUE THREAD

**Issue by sunnikbe** [anderkve/FYS3150#60]
Hi, I'm stuck. The code compiles but doesn't run. I can't figure out whats wrong and I get this error: 

> libc++abi: terminating with uncaught exception of type std::logic_error: matrix multiplication: incompatible matrix dimensions: 3x1 and 3x1
Abort trap: 6

src code:

```
// Forward Euler for particle i in PenningTrap:
void PenningTrap::evolve_fEuler(int i, arma::vec t, double h)
{
  // From particles when put into penning trap
  arma::vec r_i_0 = particles_.at(i).position();
  arma::vec v_i_0 = particles_.at(i).velocity();
  double q_i = particles_.at(i).charge();
  double m_i = particles_.at(i).mass();

  // for f function
  double x_0 = r_i_0(0);
  double z_0 = r_i_0(2);
  double v_0 = v_i_0(1);
  double w_0 = (q_i*B0_)/m_i;
  double w_z_squared = ((2.*q_i)/(m_i))*V0d_;
  double w_z = sqrt(w_z_squared);

  double w_p = w_0/2. + sqrt(w_0*w_0 - 2*w_z_squared);
  double w_m = w_0/2. - sqrt(w_0*w_0 - 2*w_z_squared);

  double A_p = (v_0 + w_m*x_0)/(w_m - w_p);
  double A_m = -(v_0 + w_p*x_0)/(w_m - w_p);

  std::complex<double> J = sqrt(-1);

  // Forward Euler:
  arma::mat r_i = arma::mat(3, t.size()).zeros();
  arma::mat v_i = arma::mat(3, t.size()).zeros();

  // Initial conditions
  r_i.col(0) = r_i_0;
  v_i.col(0) = v_i_0;

  // Forward Euler algorithm
  for (int k = 1; k < t.size(); k++)
  {
    // f function
    std::complex<double> f = A_p*exp(-J*w_p*t(k)) + A_m*exp(-J*w_m*t(k));

    double r_x = f.real();
    std::complex<double> r_y = f.imag();
    double r_z = z_0*cos(w_z*t(k));

    // Y function, position vector
    arma::vec Y = arma::vec("r_x r_y r_z");

    for (int n = 0; n == 2; n++)
    {
      v_i(n, k + 1) = v_i(n, k) + h*Y(n);
      r_i(n, k + 1) = r_i(n, k) + h*v_i(n, k);
    }
  }
  }

  printf("Velocity:\n");
  printf("Position:\n");
  v_i.print(std::cout);
  r_i.print(std::cout);
}
```

main:

```
 // Testing the forward Euler:
  int n = 10; // number of steps
  int N = n - 1; // interior points
  double h = 1./n; // stepsize

  arma::vec t = arma::linspace(0, n, N);

  trap.evolve_fEuler(0, t, h);
```

**Comment by JohanCarlsen** [comment]
Armadillo vectors are column vectors by default. You can type `vec.t()` to transpose it into a row vector, or do `mat.cols(i)=vec`.

**Comment by sunnikbe** [comment]
> Armadillo vectors are column vectors by default. You can type `vec.t()` to transpose it into a row vector, or do `mat.cols(i)=vec`.

Thank you very much but I still get the same error.

**Comment by sunnikbe** [comment]
When compiling the code with -Wall I get that r_x, r_y and r_z is unused. Does this part

```
   // f function
    std::complex<double> f = A_p*exp(-J*w_p*t(k)) + A_m*exp(-J*w_m*t(k));

    std::complex<double> r_x = f.real();
    std::complex<double> r_y = f.imag();
    double r_z = z_0*cos(w_z*t(k));

    // Y function, position vector
    arma::vec Y = arma::vec("r_x r_y r_z");
```
not work?

**Comment by JohanCarlsen** [comment]
Hmm, not sure. I used the Euler identity $$e^{i\theta}=\cos\theta+i\sin\theta$$, so i wouldn't have to deal with the imaginary part..

**Comment by anderkve** [comment]
> When compiling the code with -Wall I get that r_x, r_y and r_z is unused. Does this part not work?

Indeed. The `arma::vec` constructor that takes a string as input can only translate from a string containing literal numbers, not from a string with variable names. Here's a few examples of ways you *can* initialize an `arma::vec`, and how it fails for me when I try the approach you did above:

```cpp
#include <iostream>
#include <armadillo>
#include <vector>

using namespace std;

int main()
{

  double v0;
  double v1;

  // This works
  v0 = 1.0;
  v1 = 2.0;
  arma::vec v_a = arma::vec({v0, v1});
  cout << "v_a:" << endl << v_a << endl;


  // This works
  std::vector<double> v_init;
  v_init.push_back(v0);
  v_init.push_back(v1);
  arma::vec v_b = arma::vec(v_init);
  cout << "v_b:" << endl << v_b << endl;


  // This works
  arma::vec v_c = arma::vec("1.0 2.0");
  cout << "v_c:" << endl << v_c << endl;


  // This works
  arma::vec v_d(2);
  v_d(0) = v0;
  v_d(1) = v1;
  cout << "v_d:" << endl << v_d << endl;


  // This will fail in some strange way,
  // since armadillo can't know how to translate the 
  // string "v0" to the value of the variable v0
  // (and similar for v1)
  arma::vec v_e = arma::vec("v0 v1");
  cout << "v_e:" << endl << v_e << endl;

  return 0;
}
```

Output:
```
v_a:
   1.0000
   2.0000

v_b:
   1.0000
   2.0000

v_c:
   1.0000
   2.0000

v_d:
   1.0000
   2.0000

v_e:
        0
        0
```

**Comment by anderkve** [comment]
A couple things I noticed:

- This loop will not do anything, due to the `n == 2`. You probably meant `n <= 2`.

```cpp
    for (int n = 0; n == 2; n++)
    {
      v_i(n, k + 1) = v_i(n, k) + h*Y(n);
      r_i(n, k + 1) = r_i(n, k) + h*v_i(n, k);
    }
```

- If I am reading your code correctly, the function `PenningTrap::evolve_fEuler(int i, arma::vec t, double h)` takes as input a particle index `i`, a vector of time values `t` and then performs the *full* time evolution for particle `i`. This code design will work as long as you only have a single particle in the Penning trap. But once you start adding more particles with Coloumb interactions (Problem 8), the force acting on particle `i` at some time step will depend on the positions of all the other particles *at the same timestep*. So then I think this code design will no longer work. What rather needs to happen is that for every timestep, the positions and velocities of *all* particles in the trap are updated. My personal suggestion would be to let the `evolve_fEuler` function simply evolve the state of all particles in the `PenningTrap` by one single timestep, and then let the `main` function take care of running the loop over timesteps. (This is the design suggested by the code snippet at the bottom of the Project description.) But even if you prefer to let the `evolve_fEuler` function do the full time evolution, it needs to update all particles for every timestep.

**Comment by sunnikbe** [comment]
Okay thank you :) I changed my code to

```
// Forward Euler for particle i in PenningTrap:
void PenningTrap::evolve_fEuler(double dt)
{
  arma::mat v_new = arma::mat(3, particles_.size());
  arma::mat r_new = arma::mat(3, particles_.size());

  for (int i = 0; i < particles_.size(); i++)
  {
    arma::vec v_i = particles_.at(i).velocity();
    arma::vec r_i = particles_.at(i).position();

    v_new.col(i) = v_i + dt*r_i;
    r_new.col(i) = r_i + dt*v_i;
  }
}
```
But I still get the same error when running it;

> libc++abi: terminating with uncaught exception of type std::logic_error: matrix multiplication: incompatible matrix dimensions: 3x1 and 3x1
Abort trap: 6

**Comment by anderkve** [comment]
From a quick look I can't see any matrix multiplications (or attempted vector*vector multiplications) in any of the code you've shared here, so I suspect that error must come from somewhere else in the code? If you're not sure at what point this multiplication happens, I'd suggest just adding some cout statements throughout your code to identify the line at which it crashes. 

See e.g. tip 3 here: https://github.com/anderkve/FYS3150/tree/master/code_examples/fantastic_bugs_and_where_to_find_them. Tip 5 might also be useful.

If that doesn't help, you can always provide us with a link to the code on GitHub and we'll take a look when we can. :)

Btw, note that the current `evolve_fEuler` function as written above will not actually change the positions and velocities of the particles in the Penning trap, since the only things that are updated are the local variables `r_new` and `v_new` (these go out of scope once the `evolve_fEuler` function ends), not the positions and velocities in of the particle instances in the `particles_` container.

**Comment by sunnikbe** [comment]
> From a quick look I can't see any matrix multiplications (or attempted vector*vector multiplications) in any of the code you've shared here, so I suspect that error must come from somewhere else in the code? If you're not sure at what point this multiplication happens, I'd suggest just adding some cout statements throughout your code to identify the line at which it crashes. 
> 
> 
> 
> See e.g. tip 3 here: https://github.com/anderkve/FYS3150/tree/master/code_examples/fantastic_bugs_and_where_to_find_them. Tip 5 might also be useful.
> 
> 
> 
> If that doesn't help, you can always provide us with a link to the code on GitHub and we'll take a look when we can. :)
> 
> 
> 
> Btw, note that the current `evolve_fEuler` function as written above will not actually change the positions and velocities of the particles in the Penning trap, since the only things that are updated are the local variables `r_new` and `v_new` (these go out of scope once the `evolve_fEuler` function ends), not the positions and velocities of the particle instances in the `particles_` container. 

Thank you!! The vector multiplication error was from somewhere else in the code... 

Okay I see. I'm not entirely sure how to add the new values to the particles_ container. Should it just be something like

’’’
particles_at(i + 1).position() = ...
’’’

instead of r_new?

**Comment by anderkve** [comment]
> EDIT! -- Nvm I got it, thank you for all the help

Great, happy to hear that! :)
