### ISSUE TITLE
Armadillo linking error when generating random numbers

### ISSUE THREAD

**Issue by oysthaga** [anderkve/FYS3150#70]
When I add the lines 
`arma::vec rj = arma::vec(3).randn() * 0.1 * obj.d;`

`arma::vec vj = arma::vec(3).randn() * 0.1 * obj.d;`
I get the linking error 
> /usr/bin/ld: Main.o: in function 'TLS wrapper function for arma::arma_rng_cxx11_instance':
Main.cpp:(.text._ZTWN4arma23arma_rng_cxx11_instanceE[_ZTWN4arma23arma_rng_cxx11_instanceE]+0x25): undefined reference to 'arma::arma_rng_cxx11_instance'
collect2: error: ld returned 1 exit status

This happens whether or not I also add the line 
`arma::arma_rng::set_seed_random();`

I use the compilation and linking commands
> g++ -c Particle.cpp PenningTrap.cpp Main.cpp

> g++ -larmadillo Particle.o PenningTrap.o Main.o -o Main.exe

and get no error when I do not include those lines. 

Repo: https://github.com/oysthaga/Project-3

**Comment by anderkve** [comment]
Hi @oysthaga!

I expect it won't solve it, but could you try explicitly adding `-std=c++11` to your compilation command?

We should try to understand the reason for the linking error, but as a quick workaround for now, I'd recommend just generating the random positions and velocities you need by using some of the standard C/C++ functionality for random number generation, instead of Armadillo's built-in functionality.

Here's a minimal example of how to draw a single random number using the C++ `<random>` library: https://github.com/anderkve/FYS3150/blob/master/code_examples/random_number_generation/main_minimal.cpp

**Comment by oysthaga** [comment]
Thank you. As you expected, adding `-std=c++11` did not change anything, but the C++ `<random>` library works.
