### ISSUE TITLE
Wierd results when calculating susceptibility

### ISSUE THREAD

**Issue by JohanCarlsen** [anderkve/FYS3150#88]
Hi. I tried to solve problem 8, but I ended up with very strange results. For a 20 by 20 lattice, this is the result I get when only performing simulations on set temperature:
![Figure_1](https://user-images.githubusercontent.com/90179340/202182388-3117e7df-9379-4cbd-8dc5-1e6be745d6fc.png)
I think this looks reasonable. 
But when I'm trying to code for the range of temperature, the values are in order $10^{225}$. 
I think the error lies somewhere in my parallel implementation, which is something I find very difficult, so it is very hard to look for errors. 
```
vec tempList = linspace(2.1, 2.4, 6);
    vec L_list = vec{40, 60, 80, 100};

    results = cube(6, 2, 4);

    #ifdef _OPENMP
    {
      #pragma omp parallel
      {
        const int nThreads = omp_get_num_threads();
        const int threadID = omp_get_thread_num();
        const int weight = 1. / nThreads;

        mt19937 generator;
        unsigned int threadSeed = baseSeed + threadID;
        generator.seed(threadSeed);

        mat threadLattice;
        int L_phase;
        int N_phase;
        double T_phase;
        double threadE, threadM;
        double sumE, sumEE, sumM, sumMM;
        double avgEps, avgEps_sqrd, avgM, avgM_sqrd;
        double heatCap, X;

        for (int l = 0; l < 4; l++)
        {
          L_phase = L_list(l);
          N_phase = L_phase * L_phase;

          auto t1 = chrono::high_resolution_clock::now();

          for (int t = 0; t < 6; t++)
          {
            T_phase = tempList(t);
            threadE = E;
            threadM = M;
            sumE = 0;
            sumM = 0;
            sumMM = 0;
            threadLattice = initialize_lattice(L_phase, T_phase, threadE, threadM, false);

            for (int n = 0; n < nCyclesPerThread; n++)
            {
              mcmc(threadLattice, generator, L_phase, threadE, threadM, T_phase);

              #pragma omp critical
              {
                sumE += weight * threadE;
                sumEE += weight * threadE * threadE;
                sumM += weight * fabs(threadM);
                sumMM += weight * threadM * threadM;
              }

              avgEps = sumE / N_phase;
              avgEps_sqrd = sumEE / (N_phase * N_phase);
              avgM = sumM / N_phase;
              avgM_sqrd = sumMM / (N_phase * N_phase);

              heatCap = N_phase * (avgEps_sqrd - avgEps * avgEps) / (T_phase * T_phase);
              X = N_phase * (avgM_sqrd - avgM * avgM) / T_phase;

              results(t, 0, l) = heatCap / nCyclesPerThread;
              results(t, 1, l) = X / nCyclesPerThread;
            }
          }
```
I thought maybe here I could sum all the values for each thread and combine them in a `critical` block since I now don't divide by "n". But I don't know, maybe I'm not doing what I think at all.

**Comment by anderkve** [comment]
Hi @JohanCarlsen!

I unfortunately don't have time to look closely at it now, but some quick suggestions:

1) Take another look at the analytical expressions for how X is computed. For instance, I'm not sure I understand the logic of `X / nCyclesPerThread`. The susceptibility is a function of the averages `<M^2>` and `<M>^2`, and the computation of these depend on the number of samples (in different ways, due to the difference between "average of a squared quantity" vs "the square of an average quantity"). But X itself should not then later be normalised to the number of samples.

2) I would recommend simplifying your code by getting rid of the outermost loop over grid sizes. (I think part of your problem is connect with this loop and its connection with the parallel blocks.) The grid size L can just be a command line input, and then you run different runs for L=40, L=60, etc. So I'd suggest a two-loop structure: the outer loop over temperature and the inner loop over MC cycles, where the outer loop is parallelised as an OpenMP for loop, as per this example: https://github.com/anderkve/FYS3150/blob/master/code_examples/omp_parallelization/main_omp_outer_loop_inmem.cpp (Note the line ` #pragma omp for`.)

**Comment by JohanCarlsen** [comment]
Your suggestion to drop the outer loop worked, so I will close this issue. Thanks 👍🏽

**Comment by anderkve** [comment]
Great, happy to hear it worked! :)
