### ISSUE TITLE
Multiple deliveries before deadline

### ISSUE THREAD

**Issue by daglyd** [anderkve/FYS3150#9]
Am I not allowed to update my pdf delivery on canvas before the deadline? 
Have uploaded an unfinished pdf, but can't seem to update it.

**Comment by hafos** [comment]
I had the same problem only worse, had written a comment before uploading the PDF but Canvas interpreted that comment as the delivery so the assignment page had locked down and we couldn't upload the PDF. I had to send it on mail to Anders.

I talked to one of the group teachers and it seems like the default behaviour for the hand-in pages is to lock down after the first upload. This is not how it should be and they will change that setting for project 2 and beyond.

If I were you I would send in the newest version of the PDF on email to Anders with maybe a screenshot that you haven't modiefied it since you compiled it the last time. 

So you won't have to look it up:  anders.kvellestad@fys.uio.no

**Comment by anderkve** [comment]
Hi guys,
Thanks for letting us know about the Canvas issues -- indeed it should be possible to update the pdf until the deadline. @daglyd, feel free to just email me the final version of your pdf.

**Comment by evenmn** [comment]
This is my fault, as I set the number of allowed attempts to 1. I thought it was the number of attempts that you get feedback on, but apparently it's the total number of attempts. I apologize the trouble you got because of this, but hopefully you all managed to hand in your projects anyway. This issue will be fixed for the coming projects.

**Comment by dondondooooon** [comment]
My group just sent the final version as a comment in canvas, I hope this is okay?

**Comment by evenmn** [comment]
> My group just sent the final version as a comment in canvas, I hope this is okay?

It should be fine. You even added the comment before the deadline, so I can't see why it should be a problem :)
