### ISSUE TITLE
Expectation vs average value 

### ISSUE THREAD

**Issue by nigarabbasova** [anderkve/FYS3150#91]
Hi Anders!

This might be a bit of a silly question to ask, but I would like to double-check it nonetheless. Is it okay to use the terms expectation value and average value interchangeably? I have been a bit sloppy with it throughout the entire report, and would like to know what you think of it (and how you distinguish those two) when it comes to computing average/expectation values analytically vs numerically. I remember how you compared the two during a lecture on Project 4, but I am a bit unsure of how to apply that in the report.

Thank you! :)

**Comment by anderkve** [comment]
Hi @nigarabbasova!

Not at all a silly question -- it's a very good one! I'll reply after I'm done with some meetings.

**Comment by anderkve** [comment]
Hi again,

First, let me say that it's not a big deal for this project if you mix the terms *expectation value* and *average*, so don't worry too much about it. But to as correct as possible, I would distinguish the terms in the following way:

- *Expectation value*: This is the "true", or let's say "theoretical", expected $x$ value, denoted $E(x)$ or $\langle x \rangle$, given some probability distribution $p(x)$. It can also be referred to as the *mean* of the pdf $p(x)$. The key point is that the expectation value is a *property of the pdf*, whether or not we know its exact value. So its value does not depend on questions like how many $x$ samples we draw from $p(x)$, etc. In problem 1, when you derive analytical expressions for e.g. $\langle \epsilon \rangle$ and  $\langle \epsilon^2 \rangle$, it's therefore most correct to call these *expectation values* or *means*.

- *Average*: There are many different types of averages. (E.g. in a lecture I briefly discussed the definition from calculus for a *function average*, which isn't too relevant for Project 4.)  The type of average that is relevant for this project is of course *sample average* or *sample mean*, that is, the good ol'  $\bar{x} = \frac{1}{N} \sum x_i$. In contrast to an expectation value, the sample average is a *property of a dataset*. The proper connection between the two is that the sample average is an *estimator* for the (typically unknown) expectation value. (This is why the project description talks about e.g. "computing numerical *estimates* of $\langle \epsilon \rangle$" rather than just "computing $\langle \epsilon \rangle$ numerically".) The two quantities are only the same in the limit of infinite samples, i.e. $\lim_{N \rightarrow \infty} \bar{x} = \langle x \rangle$. So e.g. in Problem 5 a), it would technically be more correct to use a notation like $\bar{\epsilon}$ rather than $\langle \epsilon \rangle$ on the y axis of your plot. But we certainly won't be picky about that. :)

**Comment by nigarabbasova** [comment]
Thank you so much for such a detailed explanation - for someone with minimal theoretical background knowledge in statistics this was of great help! :)
